version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toutici_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=toutici
      - DB_USER=root
      - DB_PASSWORD=
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: toutici_db
    restart: always
    environment:
      MYSQL_DATABASE: toutici
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: